config/routes.rb
Coffeenated::Application.routes.draw do
  resources :rankings

  resources :roasters

  resources :coffee_types

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ranking.rb
class Ranking
  include Mongoid::Document
  include Mongoid::Timestamps

  before_create :update_coffee_average

  TASTES = %(Dark Sour Bitter Nutty Sweet Salty Floural Smokey Fruity).split.freeze
  BREW_METHODS = ['Pourover', 'Expresso', 'Drip', 'Instant', 'Percolator', 'French Press', 'Cold Brew'].freeze

  field :data, 
    type: Hash, 
    default: TASTES.each_with_object({}) { |k, h| h[k] = 0 }

  field :notes, type: String
  field :overall, type: Integer, default: 0
  field :brew_method, type: String

  belongs_to :coffee_type
  belongs_to :user

  validates :overall, presence: true
  validates :brew_method, presence: true
  validates :coffee_type, presence: true

  # before_create
  def update_coffee_average
    ranks = coffee_type.num_rankings
    avg = coffee_type.average_rankings.merge(data) { |k, avg_v, new_v|
      ((avg_v * ranks) + new_v).to_f / (ranks + 1)
    }
    avg_overall = ((coffee_type.average_overall * ranks).to_f + overall).to_f / (ranks + 1)
    coffee_type.update_attributes average_rankings: avg, num_rankings: ranks + 1, average_overall: avg_overall
  end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    @rankings = current_user.rankings.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rankings, each_serializer: RankingsIndexSerializer, root: false }
    end
  end

  def show
    @ranking = Ranking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ranking }
    end
  end

  def new
    @ranking = Ranking.new
    @autocomplete_roasters = CoffeeType.all.map { |r| 
      {label: r.name, value: r.id, category: r.roaster.name } 
    }.to_json

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ranking }
    end
  end

  def edit
    @ranking = Ranking.find(params[:id])
  end

  def create
    params[:ranking][:data].each do |k, v|
      params[:ranking][:data][k] = v.to_i
    end

    @ranking = current_user.rankings.new(params[:ranking])

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking, notice: 'Ranking was successfully created.' }
        format.json { render json: @ranking, status: :created, location: @ranking }
      else
        format.html { render action: "new" }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @ranking = Ranking.find(params[:id])

    respond_to do |format|
      if @ranking.update_attributes(params[:ranking])
        format.html { redirect_to @ranking, notice: 'Ranking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ranking = Ranking.find(params[:id])
    @ranking.destroy

    respond_to do |format|
      format.html { redirect_to rankings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.haml
= simple_form_for(@ranking) do |f|
  = f.error_notification
  .row-fluid
    .span6
      %h3 What did you think?
      .row-fluid
        .span2
          = f.label :overall, class: 'score'
        .span10
          .slider
          = f.hidden_field :overall
      - Ranking::TASTES.each do |taste|
        .row-fluid
          .span2
            = f.label taste, class: 'score'
          .span10
            .slider
            = hidden_field_tag "ranking[data][#{taste}]"
    .span6
      %h3 What are you ranking?
      = f.label "Search by Coffee"
      = text_field_tag :nada, '', id: 'roaster_autocomplete'
      = f.input :coffee_type_id, as: :hidden
      = link_to "Or Create a new coffee", new_coffee_type_path
      = f.label :brew_method
      = f.select :brew_method, Ranking::BREW_METHODS
      = f.input :notes, as: :text, input_html: { class: 'text', rows: 7 }, label: 'Some notes? (for your eyes only)'

  .form-actions
    = f.button :submit

app/views/rankings/edit.html.haml
%h1 Editing ranking

= render 'form'

= link_to 'Show', @ranking
\|
= link_to 'Back', rankings_path

app/views/rankings/index.html.haml
.well.coffee-color
  %h1 My Rankings

  %div{'ng-controller' => 'MyRankingsCtlr'}
    .row-fluid{'ng-repeat' => 'group in groups'}
      .span4{'ng-repeat' => 'ranking in group'}
        .my-rankings{id: "ranking_{{ranking.id}}"}
        %p.center
          = link_to '{{ranking.coffee_name}} by {{ranking.roaster_name}}', '/rankings/{{ranking.id}}'
    {{render_graphs()}}
  %br

  = link_to 'New Ranking', new_ranking_path

app/views/rankings/new.html.haml
= render 'form'

= link_to 'Back', rankings_path

app/views/rankings/show.html.haml
.well.coffee-color#points{'ng-controller' => 'RankingCtrlr'}
  %h3.center #{@ranking.coffee_type.roaster.name} #{@ranking.coffee_type.name}, #{@ranking.brew_method}
  .row
    .span5
      %img{src: "#{@ranking.coffee_type.maps_url}"}
    .span5.limit-height
      #ranking
        %img#coffee{src: 'http://findicons.com/files/icons/1588/farm_fresh_web/32/cup.png'}
    .span12
      %h4 Overall Rating
      #{@ranking.overall}/10
      %h4 Brew Date
      = @ranking.created_at.strftime("%m/%d/%Y")
      %h4 Notes
      = @ranking.notes.blank? ? "You didn't take any notes : (" : @ranking.notes

= link_to 'Edit', edit_ranking_path(@ranking)
\|
= link_to 'Back', rankings_path