config/routes.rb
Coffeenated::Application.routes.draw do
  resources :rankings

  resources :roasters

  resources :coffee_types

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/roaster.rb
class Roaster
  include Mongoid::Document
  field :name, type: String
  field :url, type: String
  field :image_url, type: String
  has_many :coffee_types

  validates :image_url, presence: true
  validates :url, presence: true
  validates :name, presence: true

  def average_rating
    ranks = coffee_types.map { |c| c.rankings.map(&:overall) }.flatten
    avg = ranks.inject(&:+).to_f / ranks.count
    "%.2f" % avg
  end

  def active_model_serializer
    RoasterSerializer
  end

end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  def index
    @roasters = Roaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roasters }
    end
  end

  def show
    @roaster = Roaster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @roaster }
    end
  end

  def new
    @roaster = Roaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roaster }
    end
  end

  def edit
    @roaster = Roaster.find(params[:id])
  end

  def create
    @roaster = Roaster.new(params[:roaster])

    respond_to do |format|
      if @roaster.save
        format.html { redirect_to @roaster, notice: 'Roaster was successfully created.' }
        format.json { render json: @roaster, status: :created, location: @roaster }
      else
        format.html { render action: "new" }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @roaster = Roaster.find(params[:id])

    respond_to do |format|
      if @roaster.update_attributes(params[:roaster])
        format.html { redirect_to @roaster, notice: 'Roaster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @roaster = Roaster.find(params[:id])
    @roaster.destroy

    respond_to do |format|
      format.html { redirect_to roasters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/views/roasters/_form.html.haml
= simple_form_for(@roaster) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :url
    = f.input :image_url

  .form-actions
    = f.button :submit

app/views/roasters/edit.html.haml
%h1 Editing roaster

= render 'form'

= link_to 'Show', @roaster
\|
= link_to 'Back', roasters_path

app/views/roasters/index.html.haml
%h1 Roasters

%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th # Coffees
    %th Average Rating

  - @roasters.each do |roaster|
    %tr
      %td
        = link_to roaster.name, roaster
        (#{link_to 'edit', edit_roaster_path(roaster)})

      %td= pluralize roaster.coffee_types.count, 'coffee'
      %td= roaster.average_rating

%br

= link_to 'New Roaster', new_roaster_path

app/views/roasters/new.html.haml
%h1 New roaster

= render 'form'

= link_to 'Back', roasters_path

app/views/roasters/show.html.haml
%p#notice= notice

%div{'ng-controller' => 'RoastersCtlr'}
  %h1 {{roaster.name}}
  .row-fluid
    .span8
      %img{src: '{{roaster.image_url}}'}
    .span4
      %h4 Homepage
      = link_to '{{roaster.url}}', '{{roaster.url}}'
      %h4 Top Coffees
      %div{'ng-repeat' => 'top_coffee in top_coffees'}
        %a{"ng-click" => "show_coffee(top_coffee)", "data-toggle" => "modal", :href => "#coffee_modal", :role => "button"} {{top_coffee.name}}
  %hr
  .row-fluid{'ng-repeat' => 'group in coffee_groups'}
    .span4{'ng-repeat' => 'coffee in group'}
      .row-fluid
        %h5 {{coffee.name}}
      .row-fluid
        {{coffee.description.substring(0,300) + "..."}}
      .row-fluid
        %br
        %a.btn{"ng-click" => "show_coffee(coffee)", "data-toggle" => "modal", :href => "#coffee_modal", :role => "button"} Details
  
  = render 'shared/coffee_modal'