config/routes.rb
Coffeenated::Application.routes.draw do
  resources :rankings

  resources :roasters

  resources :coffee_types

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/controllers/coffee_types_controller.rb
class CoffeeTypesController < ApplicationController
  def index
    @coffee_types = CoffeeType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coffee_types }
    end
  end

  def show
    @coffee_type = CoffeeType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coffee_type }
    end
  end

  def new
    @coffee_type = CoffeeType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coffee_type }
    end
  end

  def edit
    @coffee_type = CoffeeType.find(params[:id])
  end

  def create
    @coffee_type = CoffeeType.new(params[:coffee_type])

    respond_to do |format|
      if @coffee_type.save
        format.html { redirect_to @coffee_type, notice: 'Coffee type was successfully created.' }
        format.json { render json: @coffee_type, status: :created, location: @coffee_type }
      else
        format.html { render action: "new" }
        format.json { render json: @coffee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @coffee_type = CoffeeType.find(params[:id])

    respond_to do |format|
      if @coffee_type.update_attributes(params[:coffee_type])
        format.html { redirect_to @coffee_type, notice: 'Coffee type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coffee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coffee_type = CoffeeType.find(params[:id])
    @coffee_type.destroy

    respond_to do |format|
      format.html { redirect_to coffee_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/coffee_types_helper.rb
module CoffeeTypesHelper
end

app/views/coffee_types/_form.html.haml
= simple_form_for(@coffee_type) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.label :roaster
    = collection_select :coffee_type, :roaster_id, Roaster.all, :id, :name
    = f.input :location, label: 'Location of Origin'
    = f.input :description, as: :text

  .form-actions
    = f.button :submit, "Create Coffee"

app/views/coffee_types/edit.html.haml
%h1 Editing coffee_type

= render 'form'

= link_to 'Show', @coffee_type
\|
= link_to 'Back', coffee_types_path

app/views/coffee_types/index.html.haml
%h1 Coffees

%table
  %tr
    %th Name
    %th Roaster
    %th
    %th
    %th

  - @coffee_types.each do |coffee_type|
    %tr
      %td= coffee_type.name
      %td= coffee_type.roaster.name
      %td= link_to 'Show', coffee_type
      %td= link_to 'Edit', edit_coffee_type_path(coffee_type)
      %td= link_to 'Destroy', coffee_type, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Coffee type', new_coffee_type_path

app/views/coffee_types/new.html.haml
%h1 New Coffee

= render 'form'

app/views/coffee_types/show.html.haml
%p#notice= notice

%h1 #{@coffee_type.name} by #{link_to @coffee_type.roaster.name, @coffee_type.roaster}

%img{src: "#{@coffee_type.maps_url}"}

= link_to 'Edit', edit_coffee_type_path(@coffee_type)
\|
= link_to 'Back', coffee_types_path